AutoMation/AutoMation/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('ci_builds/', include('ci_builds.urls')),
    path('hitcount/', include('hitcount.urls', namespace='hitcount')),
    path('tracking/', include('tracking.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

AutoMation/ci_builds/urls.py
from django.urls import path

from . import views
# from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.index, name='index'),

    path('login_page/', views.login_page, name='login_page'),
    path('register_page/', views.register_page, name='reg_page'),

    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='login'),
    path('user_logout/', views.user_logout, name='logout'),

    path('bulletins/', views.bulletins, name='bulletins'),
    path('bulletin/<int:id>', views.bulletin, name='bulletin'),

    path('about_ci/', views.about, name='about'),
    path('contact_us/',views.contact, name='contact'),
    path('daily_info/',views.daily, name='daily'),
    path('ci_faq',views.faq, name='ci_faq'),
    path('static_check',views.static, name='static'),

    path('ver_maker/', views.maker, name='maker'),
    path('ver_maker/<int:project_id>', views.detail, name='detail'),

    path('ver_maker/<int:project_id>/check_sync', views.check_sync_status, name='check_sync'),
    path('ver_maker/<int:project_id>/check_sync_rpm', views.check_sync_rpm, name='check_sync_rpm'),
    path('ver_maker/<int:project_id>/start_sync', views.start_sync, name='start_sync'),
    path('ver_maker/<int:project_id>/wait_sync_end=<build_id>', views.wait_sync_end, name='wait_sync_end'),

    path('ver_maker/<int:project_id>/check_build', views.check_build_status, name='check_build'),
    path('ver_maker/<int:project_id>/check_build_rpm', views.check_build_rpm, name='check_build_rpm'),
    path('ver_maker/<int:project_id>/start_build', views.start_build, name='start_build'),
    path('ver_maker/<int:project_id>/wait_build_end=<build_id>', views.wait_build_end, name='wait_build_end'),

    path('ver_maker/<int:project_id>/check_smoke=<para>', views.check_smoke_status, name='check_smoke'),
    path('ver_maker/<int:project_id>/check_smoke_rpm=<para>', views.check_smoke_rpm, name='check_smoke_rpm'),

    path('ver_maker/<int:project_id>/start_witen', views.start_witen, name='start_witen'),
    path('ver_maker/<int:project_id>/wait_witen_end=<build_id>', views.wait_witen_end, name='wait_witen_end'),

    path('ver_maker/<int:project_id>/start_btrunc', views.start_btrunc, name='start_btrunc'),
    path('ver_maker/<int:project_id>/wait_btrunc_end=<build_id>', views.wait_btrunc_end, name='wait_btrunc_end'),

    path('ver_maker/<int:project_id>/start_tgpp', views.start_tgpp, name='start_tgpp'),
    path('ver_maker/<int:project_id>/wait_tgpp_end=<build_id>', views.wait_tgpp_end, name='wait_tgpp_end'),

    path('ver_maker/<int:project_id>/query_smoke=<para>', views.query_smoke, name='query_smoke'),

    path('ver_maker/<int:project_id>/update=<para>', views.update, name='update'),
    path('ver_maker/<int:project_id>/stop=<para>', views.stop, name='stop'),
    path('ver_maker/<int:project_id>/mail', views.mail, name='mail'),
    path('add_data/',views.add_data,name='add_data'),
    path('search/',views.search,name='search'),
]

AutoMation/ci_builds/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from hitcount.models import HitCountMixin
from ckeditor.fields import RichTextField
from datetime import date

# from config import smoke_receiver,auto_receiver
# from eSpaceAPI.send_eSpace import send_espace


class Bulletin(models.Model):
    title = models.CharField(max_length=200)
    body = RichTextField(max_length=2000)
    time = models.DateTimeField()

    class Meta:
        verbose_name = "公告管理"
        verbose_name_plural = "公告管理"

    def __str__(self):
        return self.title


class Project(models.Model, HitCountMixin):
    name = models.CharField(max_length=200)
    svn = models.CharField(max_length=1000)
    generating_path = models.CharField(max_length=1000)
    sync_serv_ip = models.CharField(max_length=100, null=True, blank=True)
    sync_proj_name = models.CharField(max_length=100, null=True, blank=True)
    build_serv_ip = models.CharField(max_length=100)
    build_proj_name = models.CharField(max_length=100)
    witen_smoke_serv_ip = models.CharField(max_length=100, null=True, blank=True)
    witen_smoke_proj_name = models.CharField(max_length=100, null=True, blank=True)
    witen_smoke_agent_ip = models.CharField(max_length=100, null=True, blank=True)
    btrunc_smoke_serv_ip = models.CharField(max_length=100, null=True, blank=True)
    btrunc_smoke_proj_name = models.CharField(max_length=100, null=True, blank=True)
    btrunc_smoke_agent_ip = models.CharField(max_length=100, null=True, blank=True)
    tgpp_smoke_serv_ip = models.CharField(max_length=100, null=True, blank=True)
    tgpp_smoke_proj_name = models.CharField(max_length=100, null=True, blank=True)
    tgpp_smoke_agent_ip = models.CharField(max_length=100, null=True, blank=True)

    class Meta:
        verbose_name = "编译工程管理"
        verbose_name_plural = "编译工程管理"

    def __str__(self):
        return self.name


BUILD_RESULT = (
    ('S', '成功'),
    ("F", '失败'),
    ("M", '强制停止'),
)


class SubRecord(models.Model):
    no = models.IntegerField()
    name = models.CharField(max_length=200)
    build_id = models.CharField(max_length=100)
    start_time = models.DateTimeField('start time', null=True, blank=True)
    duration = models.IntegerField(null=True, blank=True)
    result = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.build_id


class Record(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    sync = models.ForeignKey(SubRecord, on_delete=models.CASCADE, null=True, blank=True, related_name="sync")
    build = models.ForeignKey(SubRecord, on_delete=models.CASCADE, null=True, blank=True, related_name="build")
    witen_smoke = models.ForeignKey(SubRecord, on_delete=models.CASCADE, null=True, blank=True, related_name='witen')
    btrunc_smoke = models.ForeignKey(SubRecord, on_delete=models.CASCADE, null=True, blank=True, related_name='btrunc')
    tgpp_smoke = models.ForeignKey(SubRecord, on_delete=models.CASCADE, null=True, blank=True, related_name='tgpp')
    start_time = models.DateTimeField('start time', null=True, blank=True)
    end_time = models.DateTimeField('end time', null=True, blank=True)
    duration = models.CharField(max_length=50, null=True, blank=True, default='')
    result = models.CharField(max_length=1, choices=BUILD_RESULT, default="F", null=True, blank=True)
    url = models.CharField(max_length=1000, null=True, blank=True, default='')
    trigger = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.project.name


# 自动化记录
class Result(models.Model):
    date = models.CharField(max_length=20, null=False)
    version = models.CharField(max_length=50, null=False)
    versionpath = models.CharField(max_length=100, null=False)
    data1 = models.CharField(max_length=20, null=True)
    data2 = models.CharField(max_length=20, null=True)
    data3 = models.CharField(max_length=20, null=True)
    data4 = models.CharField(max_length=20, null=True)
    data5 = models.CharField(max_length=500, null=True)


AUTO_RESULT = (
    ("T", "通过"),
    ("F", "未通过")
)

OPTIONS = (
    ("T", "是"),
    ("F", "否")
)


# 自动化验证结果表（1）----验证版本路径及结果
class AutoRes(models.Model):
    Date = models.DateField(default=date.today, null=False, blank=False, verbose_name="日期")
    VersionNum = models.CharField(max_length=100, default="", null=False, blank=False, verbose_name="版本号")
    VersionPath = models.CharField(max_length=100, unique=True, null=False, blank=False, verbose_name="版本路径")
    res = models.CharField(max_length=1, choices=AUTO_RESULT, default="T", null=False, blank=False,
                           verbose_name="验证结果")
    options = models.CharField(max_length=10, choices=OPTIONS, default="F", null=False, blank=False, verbose_name="是否发送espace通知")

    class Meta:
        verbose_name = "自动化验证日期及路径管理"
        verbose_name_plural = "自动化验证日期及路径管理"

    def save(self, *args, **kwargs):
        receiver = auto_receiver
        title = str(self.Date) + ' 自动化验证结果已更新，点击查看'
        content = '版本号：' + str(self.VersionNum)
        if self.options == 'T':
            try:
                send_espace(receiver, title, content)
            except:
                pass
        super(AutoRes, self).save(*args, **kwargs)

    def __str__(self):
        return self.VersionPath


# 版本制式
VERSION_MODEL = (
    ("Witen", "Witen"),
    ("Btrunc", "Btrunc"),
    ("3GPP", "3GPP"),
    ("Witen-Btrunc-3GPP", "Witen-Btrunc-3GPP"),
)
# 网元
NETWORK_ELEMENT = (
    ("升级", "升级"),
    ("MDC", "MDC"),
    ("UDC", "UDC"),
    ("DC", "DC"),

)
# 验证结果
VERIFICATION_RESULT = (
    ("G", "▲"),
    ("Y", "●"),
    ("R", "■")
)
# 问题严重程度
SEVERITY_LEVEL = (
    ("1", "一般"),
    ("2", "严重"),
    ("3", "致命")
)
# 当前状态
STATUS = (
    ("1", "未定位"),
    ("2", "定位中"),
    ("3", "已定位"),
    ("4", "已解决")
)


# 自动化验证结果表（2）----详细信息
class AutoResult(models.Model):
    Time = models.TimeField(auto_now_add=True, null=False, blank=False, verbose_name="时间")
    VersionPath = models.ForeignKey(AutoRes, to_field="VersionPath", on_delete=models.CASCADE,
                                    verbose_name="版本路径")
    VersionModel = models.CharField(max_length=20, choices=VERSION_MODEL, default="Witen", null=False, blank=False,
                                    verbose_name="版本制式")
    NE = models.CharField(max_length=10, choices=NETWORK_ELEMENT, default="MDC", null=False, blank=False,
                          verbose_name="网元")
    Responsible = models.CharField(max_length=20, default="", null=False, blank=False, verbose_name="自动化测试线负责人")
    Result = models.CharField(max_length=1, choices=VERIFICATION_RESULT, default="G", null=False, blank=False,
                              verbose_name="验证结果")
    Describe = RichTextField(max_length=2000, null=True, blank=True, verbose_name="故障原因分析")

    class Meta:
        verbose_name = "自动化验证结果"
        verbose_name_plural = "自动化验证结果"


# 自动化验证结果表（3）----问题列表
class AutoProblemList(models.Model):
    DiscoveryDate = models.DateField(default=date.today, null=False, blank=False, verbose_name="问题提出日期")
    Describe = RichTextField(max_length=1000, default="", null=False, blank=False, verbose_name="问题描述")
    NE = models.CharField(max_length=10, choices=NETWORK_ELEMENT, default="MDC", null=False, blank=False,
                          verbose_name="网元")
    SeverityLevel = models.CharField(max_length=1, choices=SEVERITY_LEVEL, default="1", null=False, blank=False,
                                     verbose_name="严重程度")
    Influence = models.CharField(max_length=50, default="", null=False, blank=False, verbose_name="问题影响")
    Responsible = models.CharField(max_length=20, default="", null=False, blank=False, verbose_name="跟踪人员")
    PositioningPerson = models.CharField(max_length=20, default="", null=False, blank=False, verbose_name="定位人员/责任人")
    Status = models.CharField(max_length=20, choices=STATUS, default="1", null=False, blank=False, verbose_name="当前状态")

    def __str__(self):
        return self.Describe

    class Meta:
        verbose_name = "自动化验证问题列表管理"
        verbose_name_plural = "自动化验证问题列表管理"

    def short_describe(self):  # 在admin管理中过滤问题描述中的<p>标签，且最多只显示80个字符
        describe = str(self.Describe).replace("<p>", "")
        if len(str(describe.replace("</p>", ""))) > 80:
            return '{}......'.format(describe.replace("</p>", "")[0:80])
        else:
            return describe.replace("</p>", "")

    short_describe.allow_tags = True


SMOKEY_RESULT = (
    ("T", "通过"),
    ("F", "未通过")
)


# 冒烟结果
class SmokeyResult(models.Model):
    date = models.DateField(default=date.today, null=False, blank=False, verbose_name="日期")
    time = models.TimeField(auto_now_add=True, null=False, blank=False, verbose_name="时间")
    VersionNum = models.CharField(max_length=100, default="", null=False, blank=False, verbose_name="版本号")
    res = models.CharField(max_length=1, choices=SMOKEY_RESULT, default="T", null=False, blank=False,
                           verbose_name="冒烟结果")
    describe = RichTextField(max_length=2000, null=True, blank=True, verbose_name="问题现象及责任人")
    MDC_Btrunc = models.CharField(max_length=1, choices=SMOKEY_RESULT, default="T", null=False, blank=False)
    MDC_Witen = models.CharField(max_length=1, choices=SMOKEY_RESULT, default="T", null=False, blank=False)
    MDC_3GPP = models.CharField(max_length=1, choices=SMOKEY_RESULT, default="T", null=False, blank=False)
    MDC_IM = models.CharField(max_length=1, choices=SMOKEY_RESULT, default="T", null=False, blank=False)
    MDC_UP = models.CharField(max_length=1, choices=SMOKEY_RESULT, default="T", null=False, blank=False)

AutoMation/ci_builds/templates/ci_projects/about.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}CI建设概况{% endblock title %}


<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 定义放置文章标题的div容器 -->
<div class="container" id="main" style="margin-top: 56px">
	<div class="container" >
		<h1 class="display-3 text-primary">CI建设概况</h1>
        <hr>
        <h3>鼎桥CI的核心价值观</h3>
        <hr>
        <h5>核心目标 -- <small>&#9;一切皆配置管理;&#9;一切皆自动化</small></h5>
        <h5>核心理念 -- <small>&#9;恒者行远，思者常新，博观约取，厚积薄发，以行践言</small></h5>
        <br>
        <img src="/static/img/about.png" class="img-fluid" alt="Responsive image">
	</div>
</div>
{% endblock content %}

AutoMation/ci_builds/templates/ci_projects/bulletin.html
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}公告详情{% endblock title %}


<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 定义放置文章标题的div容器 -->
<div class="container" id="main" style="margin-top: 56px">
	<div class="container">
		<h1 class="text-primary">{{ bulletin.title }}</h1>
        <small>{{ bulletin.time }}</small>
        <hr class="my-4">
		<p>{{ bulletin.body | safe }}</p>
	</div>
</div>
{% endblock content %}

AutoMation/ci_builds/templates/ci_projects/bulletins.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}公告一览{% endblock title %}


<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 定义放置文章标题的div容器 -->
<div class="container" id="main" style="margin-top: 56px">
	<div class="container">
		<h1 class="text-center">公告一览</h1>
        <hr class="my-4">
        <div class="list-group">
        {% for bulletin in bulletin_list %}
        <a href="{% url 'bulletin' bulletin.id %}" class="list-group-item list-group-item-action">{{ bulletin.title }}
            <p class="font-weight-light">{{ bulletin.time|date:"Y-m-d H:i:s"  }}</p>
        </a>
        {% endfor %}
        </div>
	</div>
</div>
{% endblock content %}

AutoMation/ci_builds/templates/ci_projects/contact.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}联系我们{% endblock title %}


<!-- 写入 base.html 中定义的 content -->
{% block content %}

<div class="container" id="main" style="margin-top: 56px">
	<div class="container" >
		<h1 class="display-3 text-primary">联系我们</h1>
        <hr>
        <h3>CI各模块负责人</h3>
        <hr><hr>
        <p>CID负责人: 俞陈坤 ywx197548</p>
        <hr>
        <p>GIT&SVN相关: 佟梅娟 twx10656</p>
        <hr>
        <p>接口测试相关: 许勤 xwx10629</p>
        <hr>
        <p>接口工具相关: 闫华炯 ywx380766</p>
        <hr>
        <p>性能工具相关: 杨慜熠 ywx233288</p>
        <hr>
        <p>版本编译相关: 吉超 jwx457840</p>
        <hr>
        <p>SDK相关: 李得金 lwx791590</p>
        <hr>
        <p>冒烟相关: 张猛 zwx778169</p>
	</div>
</div>
{% endblock content %}

AutoMation/ci_builds/templates/ci_projects/daily.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}每日版本晴雨表{% endblock title %}


<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 定义放置文章标题的div容器 -->
<div class="container" id="main" style="margin-top: 56px">
	<div class="container">
		<h1 class="text-center">每日版本晴雨表</h1>
		<hr>
		<div class= "submitbox">
            <a href="{% url 'add_data' %}"><input class="submit" type="submit" name="submit" value="添加"/></a>
			<a href="{% url 'search' %}"><input class="submit" type="submit" name="submit" value="查询"/></a>
        </div>
	</div>
</div>
{% endblock content %}

AutoMation/ci_builds/templates/ci_projects/infos.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}信息一览{% endblock title %}


<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 定义放置文章标题的div容器 -->
<div class="container" id="main" style="margin-top: 56px">
	<div class="container">
		<h1 class="text-center">技术信息一览</h1>
        <hr class="my-4">
        {% for info in info_list %}
            <p>{{ info.title }} : <a href="{{ info.url }}">{{ info.url }}</a></p>
        {% endfor %}
	</div>
</div>
{% endblock content %}

AutoMation/ci_builds/templates/ci_projects/search.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}TTR5.3 每日版本验证结果{% endblock title %}

<!-- 适用于本html的javascript -->
{%block exscript%}
<script type="text/javascript">
    function checkForm(form){
        if($("#date").val() == "" || $("#date").val() == null){
            alert("日期不能为空，请输入......");
            return false;
        }else{
            return true;
        }
    }

</script>

{%endblock exscript%}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!--<div class="container" id="main" style="display: flex;flex-direction:column;">-->
<div class="ci_autotest" id="ci_autotest_search" style="margin-top: 56px;margin-bottom:100px;border:solid 0 red;padding:30px 0 0; width:1600px;">
    <form action="{% url 'search' %}" method="post" class="form" onsubmit="return checkForm()">
        <input type="date" name="date" id="date" style="margin:10px 100px;background: #f6f6f6;color: #202124;">
        <div id = "submitbox" style="float:right;position:relative;margin:10px 0;right:90px;height:30px;width:60px;">
            <input class="submit" type="submit" name="submit" value="查询"/>
        </div>
        {% csrf_token %}  <!-- 跨域请求 -->

        <table border="1" align="center" width="1400px" cellspacing="0" >
            <tr>
                <th class="alert alert-info" colspan="11" height="40px" style=" text-align:center; font-size:20px;border-color: black;">5.3主干版本冒烟测试报告</th>
            </tr>
            {% for smoke_result in smoke_result_list %}
                {% if smoke_result.res == "F" %}
                    <th colspan="11" style="border-color: black;color: red ;background: #d1ecf1">报告时间：{{smoke_result.date}}{{smoke_result.time}}&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp结果：{{ smoke_result.get_res_display }}</th>
                {% else  %}
                    <th colspan="11" style="border-color: black;color: green ;background: #d1ecf1">报告时间：{{smoke_result.date}}{{smoke_result.time}}&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp结果：{{ smoke_result.get_res_display }}</th>
                {% endif %}
            <tr>
                <td colspan="11" >问题现象及责任人: <br>{% autoescape off %} {{smoke_result.describe }} {% endautoescape %}</td>
            </tr>
                <tr align="center" style=" font-weight: bold">
                    <td width="126px">MDC-Btrunc </td>
                    <td width="126px">MDC-Witen </td>
                    <td width="126px">MDC-3GPP </td>
                    <td width="126px">MDC-IM </td>
                    <td width="126px">MDC-UP </td>
                    <td width="126px">UDC-EBS </td>
                    <td width="126px">UDC-OTA </td>
                    <td width="126px">UDC-UTS </td>
                    <td width="126px">ISP </td>
                    <td width="126px">SDK/DC </td>
                    <td width="126px">CID </td>
                </tr>
                <tr align="center">
                    <td>{{smoke_result.get_MDC_Witen_display}}</td>
                    <td>{{smoke_result.get_MDC_Btrunc_display}}</td>
                    <td>{{smoke_result.get_MDC_3GPP_display}}</td>
                    <td>{{smoke_result.get_MDC_IM_display}}</td>
                    <td>{{smoke_result.get_MDC_UP_display}}</td>
                    <td>{{smoke_result.get_UDC_EBS_display}}</td>
                    <td>{{smoke_result.get_UDC_OTA_display}}</td>
                    <td>{{smoke_result.get_UDC_UTS_display}}</td>
                    <td>{{smoke_result.get_ISP_display}}</td>
                    <td>{{smoke_result.get_SDK_display}}</td>
                    <td>{{smoke_result.get_CID_display}}</td>
                </tr>
                <tr>
                    <td colspan="11">版本路径：{{smoke_result.version_path}}</td>
                </tr>
            {% empty %}
                    <th style=" text-align:center">抱歉，暂未查询到结果!</th>
            {% endfor %}
        </table>
        <br>
        <br>

        <!--TTR5.3 每日版本验证结果-->
        <table colspan="11" border="1" align="center" width="1400px" cellspacing="0">
            <tbody>
            <tr>
                <th class="alert alert-info" colspan="11" height="40px" style=" text-align:center; font-size:20px;border-color: black;">TTR5.3 每日版本验证结果</th>
            </tr>
            {% for auto_res in auto_res_list %}
                <tr colspan="11" style="text-align:center">
                    <th style="text-indent:10px;">版本号:</th>
                    <th >{{auto_res.VersionNum}}</th>
                    <th style="text-indent:10px;">版本路径：</th>
                    <th colspan="11">{{auto_res.VersionPath}}</th>
                </tr>
                <!--<tr>-->
                    <!--<td colspan="8" height="25px">自动化运行情况：</td>-->
                <!--</tr>-->
                <tr colspan="11" style="text-align:center ;background: #d1ecf1;font-weight: bold">
                    <td >版本制式</td>
                    <td >网元</td>
                    <td >自动化测试线负责人</td>
                    <td >验证结果</td>
                    <td colspan="11" >故障原因分析</td>
                </tr>
                {% for auto_result in auto_res.autoresult_set.all %}
                    {% if auto_result.Result == "G" %}
                        <tr colspan="11" style="text-align:center; font-size: 14px">
                            <td>{{ auto_result.get_VersionModel_display }}</td>
                            <td>{{ auto_result.get_NE_display }}</td>
                            <td>{{ auto_result.Responsible }}</td>
                            <td style="color: green">{{ auto_result.get_Result_display }}</td>
                            <td colspan="11" width="450px" style="color: green; text-align:left">{% autoescape off %}{{ auto_result.Describe }}{% endautoescape %}</td>
                        </tr>
                    {% elif auto_result.Result == "Y" %}
                        <tr colspan="11" style="text-align:center; font-size: 14px">
                            <td>{{ auto_result.get_VersionModel_display }}</td>
                            <td>{{ auto_result.get_NE_display }}</td>
                            <td>{{ auto_result.Responsible }}</td>
                            <td style="color: #ffbe3f">{{ auto_result.get_Result_display }}</td>
                            <td colspan="11" width="450px" style="color: #ffbe3f; text-align:left">{% autoescape off %}{{ auto_result.Describe }}{% endautoescape %}</td>
                        </tr>
                    {% elif auto_result.Result == "R" %}
                        <tr colspan="11" style="text-align:center; font-size: 14px">
                            <td>{{ auto_result.get_VersionModel_display }}</td>
                            <td>{{ auto_result.get_NE_display }}</td>
                            <td>{{ auto_result.Responsible }}</td>
                            <td style="color: red">{{ auto_result.get_Result_display }}</td>
                            <td colspan="11" width="450px" style="color: red; text-align:left">{% autoescape off %}{{ auto_result.Describe }}{% endautoescape %}</td>
                        </tr>
                    {% endif %}
                {% endfor %}
                <tr>
                <td colspan="11" align="center" ><span style="font-size: 16px;margin-left: 50px;color: green ">▲代表版本验证通过</span><span style="font-size: 16px;margin-left: 50px;color: #ffbe3f">●代表版本存在非阻塞性问题</span><span style="font-size: 16px;margin-left: 50px;color: red">■代表版本验证未通过</span></td>
                </tr>
                <th style=" text-align:center">问题列表（未解决）：</th>
                <tr colspan="11" style="text-align:center ;background: #d1ecf1;font-weight: bold">
                    <td>发现日期</td>
                    <td>问题描述</td>
                    <td>问题网元</td>
                    <td>严重程度</td>
                    <td>问题影响</td>
                    <td>定位开发人员/责任人</td>
                    <td>跟踪人员</td>
                    <td>当前状态</td>
                </tr>
                {% for auto_problem in auto_problem_list %}
                    <tr style="text-align:center ;color: red">
                        <td>{{auto_problem.DiscoveryDate}}</td>
                        <td width="450px" style="text-align:left">{% autoescape off %}{{ auto_problem.Describe }}{% endautoescape %}</td>
                        <td>{{ auto_problem.get_NE_display }}</td>
                        <td>{{ auto_problem.get_SeverityLevel_display }}</td>
                        <td>{{ auto_problem.Influence }}</td>
                        <td>{{ auto_problem.PositioningPerson }}</td>
                        <td>{{ auto_problem.Responsible }}</td>
                        <td>{{ auto_problem.get_Status_display }}</td>
                    </tr>
                {% empty %}
                    <th colspan="11" style=" text-align:center">暂无</th>
                {% endfor %}
            {% empty %}
                    <th style=" text-align:center">抱歉，暂未查询到结果!</th>
            {% endfor %}
            </tbody>
        </table>

    </form>
</div>
{% endblock content %}
<div>
</div>